### ISSUE TITLE
Binary compatiblity problem in scala 2.12.3

### ISSUE THREAD

**Issue by benhutchison** [tixxit/delimited#26]
When using `delimited 0.9.0` with `scala 2.12.3`, Im seeing:
```
@ val parser: DelimitedParser = DelimitedParser(DelimitedFormat.CSV)
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: scala.math.Ordering$.$anonfun$by$1$adapted(Lscala/Function1;Lscala/math/Ordering;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  net.tixxit.delimited.RowDelim$.<init>(RowDelim.scala:28)
...
```

root cause suspected to be https://github.com/scala/bug/issues/10489

**Comment by cchantep** [comment]
Same for me with 2.12.4

**Comment by wjlow** [comment]
Upgrading to delimited 0.9.0 works with Scala 2.12.6.
